name: Automatisation des tests
on: push
jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Compilation
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          make test
          echo "Deploy"
  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction add
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          result=$(./src/calculator add 10 5)
          if [[ "$result" != "15.000000" ]]; then
            echo "Eror calcul"
            return 1
          fi
  Test_Sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction sub
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          result=$(./src/calculator sub 10 5)
          if [[ "$result" != "5.000000" ]]; then
            echo "Eror calcul"
            return 1
          fi
  Test_Mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction mul
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          result=$(./src/calculator mul 10 5)
          if [[ "$result" != "50.000000" ]]; then
            echo "Eror calcul"
            return 1
          fi
  Test_Div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction div
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          result=$(./src/calculator div 10 5)
          if [[ "$result" != "2.000000" ]]; then
            echo "Eror calcul"
            return 1
          fi
  Test_Square:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction sqaure
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          result=$(./src/calculator square 2)
          if [[ "$result" != "4.000000" ]]; then
            echo "Eror calcul"
            return 1
          fi
